name: Build Google-Drive-CI-CD
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: research-cicd

      - name: Upload APK to GCS
        run: |
          gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://research-cicd/app-release.apk

      - name: Upload APK to Google Drive
        uses: mathisve/gdrive-upload-action@v1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          file: build/app/outputs/flutter-apk/app-release.apk
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
