name: Build & Upload Flutter APK to GCS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Sesuaikan versi Flutter kamu

      # Run pub get
      - name: Install dependencies
        run: flutter pub get

      # Run build_runner
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # Build APK
      - name: Build release APK
        run: flutter build apk --release

      # Setup Google Cloud SDK
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: github-actions-gcs # Ganti sesuai project kamu

      # Upload to GCS
      - name: Upload APK to GCS
        run: |
          gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://github-action-gcs/app-release.apk
