name: Upload to Google Drive

on:
  push:
    branches:
      - main # Ganti sesuai kebutuhan

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          rclone copy ./build/output gdrive:/unplgd --drive-chunk-size=64M --progress
