# created by ncl

name: Build & Upload to GCS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: research-cicd

      - name: Upload APK to GCS
        run: |
          gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://research-cicd/app-release.apk

      - name: Trigger Apps Script to copy APK to Google Drive
        run: |
          curl -s -L 'https://script.google.com/macros/s/AKfycbwlANZJjKwX6dtEpR24zr3ZQ7AijhwS9_HIMCA33SPquSBXekCm2BrSHQoZnc9p1yy3/exec'
