# created by ncl

name: Build & Upload to GCS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: research-cicd

      - name: Upload APK to GCS
        run: |
          gsutil cp build/app/outputs/flutter-apk/app-release.apk gs://research-cicd/app-release.apk

      - name: Trigger Apps Script via Node
        run: |
          echo "const axios = require('axios');
          axios.get('https://script.google.com/macros/s/AKfycbwbvvEbsf2fTMQLvU8TmH69xXEYADS5bV2OlFBhnZokf03Wp3ZXxksyHybLhUGYJSTn2w/exec')
            .then(res => {
              console.log('✅ Triggered:', res.data);
            })
            .catch(err => {
              console.error('❌ Error:', err.message);
              process.exit(1);
            });" > trigger.js

          npm install axios
          node trigger.js

      # - name: Trigger Apps Script via wget
      #   run: |
      #     wget -qO- 'https://script.google.com/macros/s/AKfycbwbvvEbsf2fTMQLvU8TmH69xXEYADS5bV2OlFBhnZokf03Wp3ZXxksyHybLhUGYJSTn2w/exec'
